import Navbar from "@/Components/Shared/Navbar/Navbar"

export const metadata = {
  title: 'CompanyWala | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
        <Navbar/>
        <div>{children}</div>
        <h1>Footer section</h1>
    </>
  )
}